import os, json
from datetime import datetime
from crewai.tools import BaseTool
from pydantic import BaseModel, Field
from typing import Type

import sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from config import LOG_DIR, OUTPUT_DIR

class HITLInput(BaseModel):
    report:          str = Field(..., description="The clinical report generated by the Report Agent.")
    predicted_class: str = Field(..., description="CNN predicted class.")
    confidence:      float = Field(..., description="CNN confidence score.")
    image_path:      str = Field(..., description="Path to the original image.")

class HumanInTheLoopTool(BaseTool):
    name: str = "human_review_checkpoint"
    description: str = (
        "Presents the clinical report to a human reviewer (doctor) for approval or rejection. "
        "Blocks execution until the human provides a decision. Logs the decision with timestamp."
    )
    args_schema: Type[BaseModel] = HITLInput

    def _run(self, report: str, predicted_class: str,
             confidence: float, image_path: str) -> dict:

        print("\n" + "="*60)
        print("  HUMAN-IN-THE-LOOP CHECKPOINT")
        print("="*60)
        print(f"\nImage : {os.path.basename(image_path)}")
        print(f"Result: {predicted_class}  (confidence: {confidence*100:.1f}%)")
        print("\n--- GENERATED REPORT ---\n")
        print(report)
        print("\n" + "-"*60)

        while True:
            decision = input("\nDo you APPROVE this report? [yes/no/revise]: ").strip().lower()
            if decision in ("yes", "no", "revise"):
                break
            print("Please enter 'yes', 'no', or 'revise'.")

        notes = ""
        if decision in ("no", "revise"):
            notes = input("Enter your notes for revision: ").strip()

        log_entry = {
            "timestamp":      datetime.utcnow().isoformat(),
            "image":          os.path.basename(image_path),
            "predicted_class": predicted_class,
            "confidence":     confidence,
            "decision":       decision,
            "reviewer_notes": notes,
        }

        log_path = os.path.join(LOG_DIR, "hitl_decisions.json")
        history  = []
        if os.path.exists(log_path):
            with open(log_path) as f:
                history = json.load(f)
        history.append(log_entry)
        with open(log_path, "w") as f:
            json.dump(history, f, indent=2)

        if decision == "yes":
            ts = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
            out_path = os.path.join(OUTPUT_DIR, f"report_{ts}.txt")
            with open(out_path, "w") as f:
                f.write(f"DermaGuard Triage Report\n")
                f.write(f"Generated : {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')} UTC\n")
                f.write(f"Image     : {os.path.basename(image_path)}\n")
                f.write(f"Result    : {predicted_class} (confidence: {confidence*100:.1f}%)\n")
                f.write(f"Approved  : Yes\n")
                f.write("="*60 + "\n\n")
                f.write(report)
            print(f"\n✓ Report approved and saved → {out_path}")
            return {"status": "approved", "output_path": out_path, "log": log_entry}

        return {"status": decision, "reviewer_notes": notes, "log": log_entry}
